"use client";
import { Filter, Pencil, Trash2 } from "lucide-react";
import { useState } from "react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Topic } from "@/types/topic/topic";
const labels = { approved: "승인 허가", rejected: "승인 거부", pending: "승인 대기 중", unregistered: "미등록" };
export function TopicManager({ topics, loading, error, onEdit, onDelete }: { topics: Topic[]; loading: boolean; error?: Error | null; onEdit: (topic: Topic) => void; onDelete: (topic: Topic) => void }) {
 const [search,setSearch]=useState(""); const [filter,setFilter]=useState(false); const [category,setCategory]=useState("all"); const [status,setStatus]=useState("all");
 const filtered=topics.filter(t=>t.topicName.includes(search)&&(category==="all"||t.category===category)&&(status==="all"||(t.approvalStatus??"unregistered")===status));
 return <><div className="flex items-center gap-3 bg-zinc-900 rounded pr-3"><input aria-label="주제 검색" placeholder="검색" className="w-full rounded bg-zinc-900 px-3 py-3 outline-none text-zinc-100" value={search} onChange={e=>setSearch(e.target.value)}/><button aria-label="필터" aria-expanded={filter} onClick={()=>setFilter(!filter)}><Filter size={20}/></button></div>{filter&&<div className="flex gap-3"><Select value={category} onValueChange={setCategory}><SelectTrigger aria-label="카테고리 필터"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">카테고리</SelectItem>{Array.from(new Set(topics.map(t=>t.category))).filter(Boolean).map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger aria-label="승인 상태 필터"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">승인 상태</SelectItem>{Object.entries(labels).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div>}{loading&&<p className="text-zinc-400">불러오는 중...</p>}{error&&<p role="alert">{error.message}</p>}<div className="max-h-96 space-y-2 overflow-y-auto">{filtered.map(t=><div key={t.id} className="flex items-center gap-4 rounded bg-zinc-900 px-3 py-3"><span className="text-xs text-zinc-400">{t.category}</span><span className="min-w-0 flex-1 truncate">{t.topicName}</span><span>{t.questionCount??0}문항</span><span className="text-zinc-400">{t.updatedAt?new Date(t.updatedAt).toLocaleDateString("ko-KR"):"—"}</span><span>{labels[t.approvalStatus??"unregistered"]}</span><button aria-label={`${t.topicName} 편집`} onClick={()=>onEdit(t)}><Pencil size={18}/></button><button aria-label={`${t.topicName} 삭제`} onClick={()=>onDelete(t)}><Trash2 size={18}/></button></div>)}</div></>;
}
